version: '3.9'
services:
  server:
    build: .
    command: gunicorn app:app --bind 0.0.0.0:80 --reload -t 600
    ports:
      - 80:80
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
