version: '3.9'
services:
  server:
    build: .
    command: gunicorn app:app --bind 0.0.0.0:5000 --reload
    ports:
      - 5000:5000
    volumes:
      - ../models:/environment/models
      - ../scalers:/environment/scalers
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URI: 'postgresql://islam:123123@db/stocks'
    depends_on:
      - db
    links:
      - db

  db:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: 'islam'
